export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//Delivery Option
export const UPDATE_SELECTED_OPTION_TYPE = 'UPDATE_SELECTED_OPTION_TYPE';
export const ENABLE_PRODUCT_PREVIEW = 'ENABLE_PRODUCT_PREVIEW';
export const DISABLE_PRODUCT_PREVIEW = 'DISABLE_PRODUCT_PREVIEW';
export const UPDATE_DELIVERY_OPTION_BASKET_ITEMS = 'UPDATE_DELIVERY_OPTION_BASKET_ITEMS';
export const UPDATE_DELIVERY_OPTIONS = 'UPDATE_DELIVERY_OPTIONS';
export const UPDATE_DELIVERY_GROUPS = 'UPDATE_DELIVERY_GROUPS';
export const UPDATE_FOCUS_ITEM = 'UPDATE_FOCUS_ITEM';
